# TrajectoryPlannerROS:
#     max_vel_x: 0.1
#     min_vel_x: 0.01
#     max_vel_theta: 0.1
#     min_in_place_vel_theta: 0.05

#     acc_lim_theta: 1.0
#     acc_lim_x: 1.0
#     acc_lim_y: 1.0

#     holonomic_robot: false


DWAPlannerROS:
  max_vel_trans: 0.3 #0.1
  min_vel_trans: -1.0
  max_vel_x: 0.3
  min_vel_x: -1.0
  max_vel _y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 0.7 #0.5
  min_vel_theta: -0.7 #-0.5
  acc_lim_x: 2.0
  acc_lim_y: 0.0
  acc_lim_theta: 5.0
  acc_lim_trans: 2.0
  min_in_place_vel_theta: 1.0 #new

  prune_plan: false

  xy_goal_tolerance: 0.1 #0.05
  yaw_goal_tolerance: 0.1 #0.3,0.9
  trans_stopped_vel: 0.1
  theta_stopped_vel: 0.1
  sim_time: 1.0 #0.3
  sim_granularity: 0.05 #0.1
  angular_sim_granularity: 0.05 #0.1
  path_distance_bias: 34.0 #34
  goal_distance_bias: 24.0 #24.0
  occdist_scale: 0.2 #0.05
  twirling_scale: 0.0
  stop_time_buffer: 0.5
  oscillation_reset_dist: 0.05 #0.3
  oscillation_reset_angle: 0.2
  forward_point_distance: 0.3
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  # controller_frequency: 30

  use_dwa: true

#base_local_planner: teb_local_planner/TebLocalPlannerROS

# TebLocalPlannerROS:
#   odom_topic: /odometry/filtered
#   map_frame: map

#   # Trajectory
 
  # # GoalTolerance

  # xy_goal_tolerance: 0.1
  # yaw_goal_tolerance: 0.05
  # free_goal_vel: False #False

  # # Obstacles

  # min_obstacle_dist: 0.3 # minimum distance to obstacle: it depends on the footprint_model
  # include_costmap_obstacles: True # use the local costmap
  # costmap_obstacles_behind_robot_dist: 1.0 # distance at which obstacles behind the robot are taken into account
  # obstacle_poses_affected: 30 # unused if legacy_obstacle_association is false
  # inflation_dist: 0.7 # greater than min_obstacle_dist to take effect
  # legacy_obstacle_association: false
  # obstacle_association_force_inclusion_factor: 1.5 # the obstacles that will be taken into account are those closer than min_obstacle_dist*factor, if legacy is false
  # obstacle_association_cutoff_factor: 5.0 # the obstacles that are further than min_obstacle_dist * factor will not be taken into account, if legacy is false
  # costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  # costmap_converter_spin_thread: True
  # costmap_converter_rate: 5
  
  # Optimization

  # no_inner_iterations: 5
  # no_outer_iterations: 4
  # optimization_activate: True # optimize
  # optimization_verbose: False
  # penalty_epsilon: 0.1
  # weight_max_vel_x: 20
  # weight_max_vel_y: 0
  # weight_max_vel_theta: 20
  # weight_acc_lim_x: 1
  # weight_acc_lim_y: 0
  # weight_acc_lim_theta: 1
  # weight_kinematics_nh: 10000 # is a nonholonomic robot
  # weight_kinematics_forward_drive: 10 # prefer forward driving, for differential
  # weight_kinematics_turning_radius: 1 # prefer turns that respect the min_turning_radius, not used if differential (min_turning_radius = 0)
  # weight_optimaltime: 10 # prefer trajectories with less transition time
  # weight_obstacle: 50 # prefer trajectories that respect the min_obstacle_dist
  # weight_inflation: 1 # prefer trajectories that respect the inflation of the obstacles
  # #weight_dynamic_obstacle: 10 # not in use yet
  # weight_viapoint: 100 # prefer trajectories that respect the viapoints in the global path
  # weight_adapt_factor: 2 # factor to multiply some weights (currently only weight_obstacle) at each iteration (gives better results than a huge value for the weight)

  # # Homotopy Class Planner

  # enable_homotopy_class_planning: False # currently not used
  # simple_exploration: False
  # enable_multithreading: True
  # max_number_classes: 4
  # selection_cost_hysteresis: 1.0
  # selection_obst_cost_scale: 4.0
  # selection_viapoint_cost_scale: 1.0
  # selection_alternative_time_cost: False
  # roadmap_graph_no_samples: 15
  # roadmap_graph_area_width: 6
  # h_signature_prescaler: 1.0
  # h_signature_threshold: 0.1
  # obstacle_heading_threshold: 0.45
  # roadmap_graph_no_samples: 15
  # roadmap_graph_area_width: 5
  # obstacle_keypoint_offset: 0.1
  # visualize_hc_graph: False