obstacle_range: 3.5
raytrace_range: 5.0
#footprint: [[-0.15, -0.15], [-0.15, 0.15], [0.15, 0.15], [0.15, -0.15]]
robot_radius: 0.2
inflation_radius: 0.4
transform_tolerance: 0.5

observation_sources: scan
scan:
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true
  inf_is_valid: true

map_type: costmap

# obstacle_range: 2.5
# raytrace_range: 3.0
# robot_radius: 0.5
# inflation_radius: 0.55

# observation_sources: laser_scan_sensor

# laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true}
