# local_costmap:
#   global_frame: map
#   robot_base_frame: base_link
#   update_frequency: 1.0
#   publish_frequency: 5.0
#   static_map: false
#   rolling_window: true
#   width: 6.0
#   height: 6.0
#   resolution: 0.05

local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 3.0 #before 5.0
  publish_frequency: 1.0 #before 2.0
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.025 #increase to for higher res 0.025
  transform_tolerance: 0.5
  cost_scaling_factor: 3.0
  inflation_radius: 0.4
  track_unknown_space: false

  # plugins:
  # - {name: static_layer,           type: "costmap_2d::StaticLayer"}
  # - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}