base_global_planner: global_planner/GlobalPlanner
#base_global_planner: navfn/NavfnROS
#base_local_planner: teb_local_planner/TebLocalPlannerROS
base_local_planner: dwa_local_planner/DWAPlannerROS

shutdown_costmaps: false

controller_frequency: 5.0 #before 3.0
controller_patience: 3.0 # before 2.0

planner_frequency: 0.5 #1.0
planner_patience: 3.0

oscillation_timeout: 15.0
oscillation_distance: 0.1

conservative_reset_dist: 0.1 #distance from an obstacle at which it will unstuck itself

max_planning_retries: -1

cost_factor: 0.8
neutral_cost: 66
lethal_cost: 253

